### ISSUE TITLE
Once the monster touches the side of a building, it cannot move - it can only fire.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#12] opened 2020-10-31 20:38 UTC
![image](https://user-images.githubusercontent.com/63676047/97789517-86c4fb00-1b97-11eb-98e3-f0c703f916c5.png)

**Comment by maitian352** [comment] 2020-10-31 21:36
This is a duplicate of [this](https://github.com/maitian352/Meadow-Guarder/issues/14), where when the monster gets to you it stops tracking you.

**Closed by maitian352** 2020-10-31 21:36 UTC
Labels: bug, duplicate, fixed
