### ISSUE TITLE
I managed to sign in three times!

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#120] opened 2020-11-15 18:50 UTC
![image](https://user-images.githubusercontent.com/63676047/99193838-773ada00-2773-11eb-91ca-573722ac4082.png)
It never said I logged off and I managed to sign on three times.

**Comment by maitian352** [comment] 2020-11-15 19:10
This is a duplicate of #46.

**Closed** 2020-11-21 22:16 UTC
Labels: bug, cool, duplicate, fixing, good first issue, please confirm
