### ISSUE TITLE
ten-eyed-one getst stuck on nothing

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#135] opened 2021-11-27 01:41 UTC
dont have screenshot

**Comment by Suvanth-Erranki** [comment] 2021-11-27 01:56
I do have a screenshot.
![image](https://user-images.githubusercontent.com/76885647/143664555-56b0288c-5cd6-4b08-997e-02b3fa4c38c1.png)

**Comment by Suvanth-Erranki** [comment] 2021-11-27 01:57
Duplicate of #133

**Closed by Suvanth-Erranki** 2021-11-27 01:57 UTC
