### ISSUE TITLE
Once monster goes on top of a building, it disappears and neither you or it can hurt the other.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#14] opened 2020-10-31 20:43 UTC
If you are on top of a building, the monster can follow you to the top and once it comes on top of the buidling, it disappears and you can only see its health. It doesn't shoot at you and it can't move. If you try to shoot at it, you will fail to hurt it.
![image](https://user-images.githubusercontent.com/63676047/97789601-21bdd500-1b98-11eb-95dd-80e4dce5212c.png)

**Comment by maitian352** [comment] 2020-10-31 21:36
This is a duplicate of [this](https://github.com/maitian352/Meadow-Guarder/issues/12), where when the monster gets to you it stops tracking you.

**Closed by maitian352** 2020-10-31 21:36 UTC
Labels: bug, duplicate, fixed
