### ISSUE TITLE
the monster gets stuck on trees this is a glich but im a bug finder

### ISSUE THREAD

**Issue by itsferytime** [maitian352/Meadow-Guarder#160] opened 2021-11-30 14:52 UTC
![image](https://user-images.githubusercontent.com/94699229/144069830-9ae1249b-be95-4cbd-8e98-ba41f260edc9.png)

**Comment by itsferytime** [comment] 2021-11-30 14:52
![image](https://user-images.githubusercontent.com/94699229/144069830-9ae1249b-be95-4cbd-8e98-ba41f260edc9.png)

**Comment by itsferytime** [comment] 2021-11-30 14:52
see look

**Comment by definitely-nobody-is-here** [comment] 2021-11-30 17:17
It’s a bug

**Comment by definitely-nobody-is-here** [comment] 2021-11-30 17:18
Duplicate of #133

**Comment by itsferytime** [comment] 2021-11-30 18:43
so i found a bug oooo

**Comment by maitian352** [comment] 2021-12-01 01:37
Why is this closed? It isn't fixed yet.

**Comment by Suvanth-Erranki** [comment] 2021-12-01 02:00
> Why is this closed? It isn't fixed yet.

It's a duplicate and duplicates are closed.

**Comment by maitian352** [comment] 2021-12-01 02:00
> > Why is this closed? It isn't fixed yet.
> 
> It's a duplicate and duplicates are closed.

Duplicates should not be closed.

**Comment by maitian352** [comment] 2021-12-15 23:10
I believe this is fixed. Reopen if still happening.

**Closed by maitian352** 2021-12-15 23:10 UTC
Labels: bug, duplicate, fixed, hard, please confirm
