### ISSUE TITLE
my screen is grey what

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#146] opened 2021-11-29 00:42 UTC
![image](https://user-images.githubusercontent.com/67865358/143793281-28105b30-adaa-489f-84ba-050d4963f352.png)

**Comment by Suvanth-Erranki** [comment] 2021-11-29 00:58
its gray not grey

**Comment by Suvanth-Erranki** [comment] 2021-11-29 00:58
duplicate of #138

**Comment by definitely-nobody-is-here** [comment] 2021-11-29 16:21
British spelling is “grey”

**Comment by Suvanth-Erranki** [comment] 2021-11-30 23:49
Hello british mate.

**Closed** 2021-12-31 14:59 UTC
Labels: bug, help wanted, question, fixed, confusing
