### ISSUE TITLE
npc dialoge doesnt close when you leave the map

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [maitian352/Meadow-Guarder#132] opened 2021-11-27 00:53 UTC
still a problem
shops close but npc dialoge doesnt

**Comment by definitely-nobody-is-here** [comment] 2021-11-27 00:54
also I can still open shops in the wrong map this way
![image](https://user-images.githubusercontent.com/67865358/143663055-d37e86d2-35d0-4dd2-89ad-0735e6f0f2b7.png)

**Comment by Suvanth-Erranki** [comment] 2021-11-27 00:56
Mistake.

**Comment by Suvanth-Erranki** [comment] 2021-11-27 00:57
I don't really think this an issue, since its helpful to see what an NPC said if you are doing a quest and it is giving you instructions. This can help you remember what you need to do.

**Comment by Suvanth-Erranki** [comment] 2021-11-27 00:57
Duplicate of #128

**Comment by Suvanth-Erranki** [comment] 2021-11-27 00:58
Should I close?

**Closed** 2021-11-27 00:59 UTC
Labels: duplicate, enhancement, fixed
