### ISSUE TITLE
Monsters get stuck bouncing in this spot:

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#168] opened 2020-12-08 17:50 UTC
The monster kept bouncing up and down here:
![image](https://user-images.githubusercontent.com/63676047/101521549-ff1b9a80-3953-11eb-93a9-c83d81893a8c.png)

**Comment by maitian352** [comment] 2020-12-08 17:51
It isn't just this spot, this happens in other places too.

**Comment by maitian352** [comment] 2020-12-09 21:49
I think this is fixed. Reopen this if it isn't.

**Comment by Suvanth-Erranki** [comment] 2020-12-10 15:38
Still happening.

**Comment by maitian352** [comment] 2020-12-10 15:40
This is a duplicate of #160, and the bouncing is the monster running away from you.

**Closed by maitian352** 2020-12-10 15:40 UTC
Labels: bug, critical, help wanted, important, please confirm

**Comment by maitian352** [comment] 2021-04-20 20:16
There was a comment on another issue, but was meant to be posted here. This happened again, and the monster was on full health. This is because the monster healed.
