### ISSUE TITLE
Sometimes monsters don't die when you fire at them.

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#93] opened 2020-11-09 15:51 UTC
View this video to see the glitch:
https://drive.google.com/file/d/1-aKxK6wdLqcDv81dTsfukpa31nVqkGSY/view
Note: I could kill every monster around the area except for that monster.

**Comment by maitian352** [comment] 2020-11-09 15:52
This bug is a duplicate of [this](https://github.com/maitian352/Meadow-Guarder/issues/73).

**Closed** 2020-11-09 15:53 UTC
Labels: bug, critical, duplicate, good first issue, help wanted, important

**Comment by maitian352** [comment] 2020-11-09 18:17
Fixed.

**Comment by Suvanth-Erranki** [comment] 2020-11-09 18:18
Great job Maitian!
